### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by jrenaf** [hsimho/MightyL#1]
Hello, when I tried to compile the code with make, it gave the error of 
`[ 37%] Building CXX object CMakeFiles/mightyl.dir/main.cpp.o
/home/jren313/Documents/MightyL/main.cpp:11:10: fatal error: TA.h: No such file or directory
   11 | #include "TA.h"
      |          ^~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mightyl.dir/build.make:111: CMakeFiles/mightyl.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:344: CMakeFiles/mightyl.dir/all] Error 2
`
My guess is that it didn't compile MoniTAal first before it started mightyL and tried to build main.cpp.

**Comment by hsimho** [comment]
Since you have managed to compile - I opt to close it.
