### ISSUE TITLE
Error while building TA

### ISSUE THREAD

**Issue by jrenaf** [hsimho/MightyL#2]
Hello, I managed to compile and run it anyway, but when I fed in the formula you gave in .mitl files, the program gave the following error:

```
mightyl: ~/Documents/MightyL/MightyL.cpp:3428: monitaal::TA mightylcpp::build_ta_from_main(mightylcpp::MitlParser::MainContext*): Assertion `std::any_cast<bool>(check_nnf_visitor.visitMain(nnf_formula))' failed.
Aborted (core dumped)
```

Do you have any idea how to solve it? 
Thanks.

**Comment by hsimho** [comment]
Hi, it's just that the current version does not support intervals like `[1, 2]` (as noted in the README)!
